version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8040:80
    container_name: reverse-proxy
    depends_on:
      - server
      
  server:
    image: todo-server
    container_name: todo-server
    build: ./todo-backend
    ports:
      - 3001:3001
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/the_database
    depends_on:
      - mongodb
      - redis

  client:
    image: todo-client
    build: ./todo-frontend
    container_name: todo-client

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis:6.2
    container_name: redis
    ports:
     - 6379:6379

    volumes:
      - ./todo-backend/redis_data:/var/lib/redis
    command: ['redis-server', '--appendonly', 'yes']

  debug-helper:
      image: busybox