version: '3.8'

services:
  app:
    image: client
    build: ./todo-frontend
    container_name: client
    ports:                
      - 3000:3000

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8040:80
    container_name: reverse-proxy